### ISSUE TITLE
RISC-V code generation

### ISSUE THREAD

**Issue by jserv** [jserv/shecc#10]
Per the request of @lazyparser, `shecc` would support RISC-V code generation and still self-host.

**Comment by lazyparser** [comment]
Thanks ;-)

is there any guidelines for new backends contribution?

I'd like to contribute

**Comment by MikeDB1** [comment]
I'd also comment that ARM 64 bit support would be useful.  The Pi4 is much more efficient on 64bit and some processors are already 64 bit only

**Comment by eecheng87** [comment]
Hi, I try to contribute this feature recently. Before started, I want to make sure that my modification is under your expectation and approval. Following is high level description about what I'll do:

* Add parameter (argc/argv) to decide target (RISC-V or ARM)
* Modify code in `codegen.c` to support emitting ARM or RISC-V instruction
* Add new file `riscv.c` to mapping instruction emit by `codegen.c` into RISC-V bytecode

Also, I've some question about how to verify result compiled in RISC-V bytecode? Is it as same as how to verify ARM-based result? Are there any RISC-V simulator you like me to use as we run ARM bytecode on `qemu`.

Any suggestion is appreciated!

**Comment by lazyparser** [comment]
> Hi, I try to contribute this feature recently. Before started, I want to make sure that my modification is under your expectation and approval. Following is high level description about what I'll do:
> 
>     * Add parameter (argc/argv) to decide target (RISC-V or ARM)
> 
>     * Modify code in `codegen.c` to support emitting ARM or RISC-V instruction
> 
>     * Add new file `riscv.c` to mapping instruction emit by `codegen.c` into RISC-V bytecode
> 
> 
> Also, I've some question about how to verify result compiled in RISC-V bytecode? Is it as same as how to verify ARM-based result? Are there any RISC-V simulator you like me to use as we run ARM bytecode on `qemu`.
> 
> Any suggestion is appreciated!

Fantastic!

Spike and QEMU are both the emulator we daily use.

https://github.com/riscv/riscv-isa-sim is the repo of spike.

The easiest way to deploly QEMU on linux/ubuntu can ref:
https://github.com/isrc-cas/PLCT-Toolbox/blob/master/deploy_riscv64fedora_qemu.sh

for a user-level binary, the user mode QEMU is very handy. the usage of qemu-riscv64/qemu-riscv32 is much like the QEMU-arm shecc used. 

For the RISC-V, currently RV64G is more mature than the RV32G platform. But for an educational compiler, RV32I might be good & precise enough.

**Comment by jserv** [comment]
> Following is high level description about what I'll do:
> * Add parameter (argc/argv) to decide target (RISC-V or ARM)
> * Modify code in `codegen.c` to support emitting ARM or RISC-V instruction
> * Add new file `riscv.c` to mapping instruction emit by `codegen.c` into RISC-V bytecode

No runtime options are required to switch between Arm and RISC-V targets. Instead, let's use build-time options for selecting the requested target.

The current `src/codegen.c` can be renamed to `src/arm-codegen.c` and the build system can prepare symbolic link `src/codegen.c` to it, which minimizes the changes against the existing codebase.

I have written partial `src/riscv.c` for generic RISC-V opcode encoding. It will appear in some dedicated branch later.

**Comment by jserv** [comment]
RISC-V port of shecc is work in process: https://github.com/jserv/shecc/tree/wip/riscv-backend
At present, RISC-V instruction encoding, preliminary RISC-V code generation, and ELF writer are implemented. Use `qemu-riscv32` to execute the generated ELF file.
@eecheng87, please rework on top of this branch.

**Comment by eecheng87** [comment]
@jserv , thanks for your update. Is it normal that get segmentation fault while using `qemu-riscv32` to execute generated ELF file?

**Comment by jserv** [comment]
> @jserv , thanks for your update. Is it normal that get segmentation fault while using `qemu-riscv32` to execute generated ELF file?

Yes, it was an expected result.

**Comment by eecheng87** [comment]
> > @jserv , thanks for your update. Is it normal that get segmentation fault while using `qemu-riscv32` to execute generated ELF file?
> 
> Yes, it was an expected result.

I don't think it cause by more code need to implement because the code you have written seems enough to generate simple ELF file. 

It seems to me that there're some bugs in code you given. Have you suspected any possible about fail to generate ELF file?

Thanks!

**Comment by jserv** [comment]
> It seems to me that there're some bugs in code you given. Have you suspected any possible about fail to generate ELF file?

You have to validate the code generator by touching simple programs. That is the reason why we prepared the test suite.

**Comment by jserv** [comment]
> RISC-V port of shecc is work in process: https://github.com/jserv/shecc/tree/wip/riscv-backend
> At present, RISC-V instruction encoding, preliminary RISC-V code generation, and ELF writer are implemented. Use `qemu-riscv32` to execute the generated ELF file.

@eecheng87 is reworking the RISC-V code generation and runtime support. See #40

**Comment by jserv** [comment]
@lazyparser, Finally, `shecc` supports RISC-V code generation along with self-hosting! Please check out the latest `master` branch.
