### ISSUE TITLE
Is there any teaching materials available with shecc

### ISSUE THREAD

**Issue by lazyparser** [jserv/shecc#11]
Hi @jserv 

I'd like to use shecc in my personal compiler MOOC.
I am using <Engineering a Compiler> as textbook, and RISC-V as target backend.
Is there any teaching materials available with shecc now?
If not, is there a way to contribute?

**Comment by jserv** [comment]
> I'd like to use shecc in my personal compiler MOOC.
> I am using as textbook, and RISC-V as target backend.
> Is there any teaching materials available with shecc now?
> If not, is there a way to contribute?

There is no teaching materials for shecc. I did this project in my spare time. I am inviting my students to overcome the known issues. However, the progress is quite early though.

**Comment by lazyparser** [comment]
Thank you for sharing this excellent project! Hopefully I might share some teaching tutorials/talks once I finished.

**Comment by jserv** [comment]
Close this issue in favor of further detailed ones.
