### ISSUE TITLE
Fail to write global variable

### ISSUE THREAD

**Issue by eecheng87** [jserv/shecc#12]
Hi, I am trying to add feature: global variable initialization.
I modify some code and it seems good when I dump IR, following is simple sample
```
...
0x000122d4         x1 := 44
0x000122d8         x0 = &a
0x000122e0         *x0 = x1 (4)
0x000122e4     main:
0x000122fc         {
0x000122fc             x0 := &data[36]
0x00012304             x1 = &a
0x0001230c             x1 = *x1 (4)
0x00012310             x0 := printf() @ 978
0x00012314             x0 := 0
0x00012318             return (from main)
0x0001231c         }
0x0001231c         exit main
```
corresponding C code

```cpp
int a = 44;
int main(int argc, char *argv[])
{
    printf("%d\n", a);
    return 0;
}
```

As I mention, it seems good for assigning initial value to `a` in IR, but the value printed is 0. This weird stuff stuck me a few day. Anything I ignore about writing value to global variable? Thanks!

**Comment by jserv** [comment]
It is a known issue that global variable initialization is *not* supported. Therefore, you can not initialize a global such as `int i = [expr]`. In order to resolve this issue, we have to implement a pointer to bss/data section in code generation.
