### ISSUE TITLE
Questions about Op Priority

### ISSUE THREAD

**Issue by MegaYP** [jserv/shecc#3]
In "get_operator_prio(opcode_t op)" in line 836, cfront.c,
what is the reason you put lower priority Op in the front and lower priority Op in the rear?

If for reducing the clock cycle, 
isn't the way should be putting the most used Operation in the front?

**Comment by jserv** [comment]
It is just a common trick to reduce necessary tokens. Generally, you can always rewrite the following:
```c
if (x > 100)
    return -1;
else if (x < 1)
    return -1;
else
    return x;
```

into
```c
if (x > 100)
    return -1;
if (x < 1)
    return -1;
return x;
```

Sometimes, the later form looks cleaner.
