### ISSUE TITLE
qemu: uncaught target signal 4 (Illegal instruction) - core dumped

### ISSUE THREAD

**Issue by dougpuob** [jserv/shecc#4]
I tried to have fun with instructions with README.md, but got error like the following,

``` bash
$ make
  SHECC	out/shecc-stage2.elf
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
make: *** [Makefile:59: out/shecc-stage2.elf] Illegal instruction (core dumped)
```

Then I made a simple test,
1. Passed to execute native `shecc` binary on host.
2. Failed to execute `shecc-stage2.elf` with `qemu-arm shecc-stage2.elf hello.c` command.

![2020-09-06_101439](https://user-images.githubusercontent.com/3453968/92316650-e4224d00-f029-11ea-99ea-a1b8ba0afa73.png)

**Comment by jserv** [comment]
It might be an issue when qemu user emulation selects the targets. Execute `qemu-arm -cpu help` to get the supported machine list. For `shecc`, Cortex-A series cores are expected. So, you can run the following command:
```shell
qemu-arm -cpu cortex-a9 out/shecc-stage1.elf hello.c 
```

Please let me know if it works or not.

**Comment by dougpuob** [comment]
> It might be an issue when qemu user emulation selects the targets. Execute `qemu-arm -cpu help` to get the supported machine list. For `shecc`, Cortex-A series cores are expected. So, you can run the following command:
> 
> ```shell
> qemu-arm -cpu cortex-a9 out/shecc-stage1.elf hello.c 
> ```
> 
> Please let me know if it works or not.

Doesn't work still even did it with a newer qemu v5.1.1

![2020-09-06_224743](https://user-images.githubusercontent.com/3453968/92328430-511dfd00-f093-11ea-9190-82299f3d0b6f.png)

**Comment by jserv** [comment]
Please do not reply with screenshots which only contain text messages. It would be less efficient for reading and reproducing.

**Comment by jserv** [comment]
Confirmed with qemu `v5.1.0`.
> `./configure --target-list=arm-linux-user`

**Comment by dougpuob** [comment]
> Please do not reply with screenshots which only contain text messages. It would be less efficient for reading and reproducing.

Got it, it's make sense. 

There is a typo above, I have fixed. (v5.1.1 --> v5.1.0)
