### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by WilliamWangPeng** [jserv/shecc#53]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220941-766a7280-bb1f-11eb-8353-ab38fbc2ef80.png)

thank you  
best regards to you  
William

**Comment by jserv** [comment]
Hi @WilliamWangPeng, thanks for your interest. Unfortunately, `shecc` is not a general C compiler, that implies being unable to compile arbitrary C programs. Only a few C programs are known to work with `shecc`.
